<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hearthstone" nsURI="http://hearthstone/1.0" nsPrefix="hearthstone">
  <eClassifiers xsi:type="ecore:EClass" name="Card">
    <eOperations name="UpdateCardStates" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="CardStates" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="InteractAnotherCard">
      <eParameters name="thecard" eType="#//Card"/>
    </eOperations>
    <eOperations name="ShowCard"/>
    <eOperations name="InteractOppoHero">
      <eParameters name="theHero" eType="#//Hero"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CardName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CardCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CardLife" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CardPower" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CardQuality" eType="#//CardQuality">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Quality means:&#xD;&#xA;1 - normal&#xD;&#xA;2 - rare&#xD;&#xA;3 - epic&#xD;&#xA;4 - legedary"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CardNumberLimit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="wildcards" value=""/>
        <details key="name" value=""/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CardRace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Race means:&#xD;&#xA;1 - Normal minion&#xD;&#xA;2 - Beast&#xD;&#xA;3 - Pirate&#xD;&#xA;4 - Spell&#xD;&#xA;5 - Weapon"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CardStates" eType="#//CardStates">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="States means the card is:&#xD;&#xA;In deck - 1&#xD;&#xA;In hand - 2&#xD;&#xA;Sleep -10&#xD;&#xA;Active - 11&#xD;&#xA;Destory - 99"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CardClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CardHasAbilities" upperBound="5"
        eType="#//Ability" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CardSN" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CardAbilityDesc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CardDeckSN" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deck">
    <eOperations name="Hello" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="ShowVersion"/>
    <eOperations name="ShowCardsInDeck"/>
    <eOperations name="FlushDeck"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DeckID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DeckName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DeckHasCards" ordered="false"
        lowerBound="30" upperBound="30" eType="#//Card" containment="true" eKeys="#//Card/CardDeckSN"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DeckHasHero" lowerBound="1"
        eType="#//Hero"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ability">
    <eOperations name="Charge" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="IncreaseAttribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AbilityID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AbilityType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AbilityAffect" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CardHasAbility" upperBound="5"
        eType="#//Card" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CardQuality">
    <eLiterals name="Normal"/>
    <eLiterals name="Rare" value="1"/>
    <eLiterals name="Epic" value="2"/>
    <eLiterals name="Legedary" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CardRace">
    <eLiterals name="Normal"/>
    <eLiterals name="Beast" value="1"/>
    <eLiterals name="Pirate" value="2"/>
    <eLiterals name="Skill" value="3"/>
    <eLiterals name="Spell" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Abilities" instanceClassName="hearthstone.Ability"/>
  <eClassifiers xsi:type="ecore:EEnum" name="HeroClass">
    <eLiterals name="Mage"/>
    <eLiterals name="Priest" value="1"/>
    <eLiterals name="Paladin" value="2"/>
    <eLiterals name="Warlock" value="3"/>
    <eLiterals name="Hunter" value="4"/>
    <eLiterals name="Rogue" value="5"/>
    <eLiterals name="Druid" value="6"/>
    <eLiterals name="Warrior" value="7"/>
    <eLiterals name="Shaman" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GamePlayerHand" eSuperTypes="#//GameDeck">
    <eOperations name="ShowGameHand"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CardsInHand" upperBound="10"
        eType="#//Card" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HandOwner" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameBoard">
    <eOperations name="ShowGameBoard">
      <eParameters name="pindex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GameBoardHasPlayerBoard"
        lowerBound="2" upperBound="-1" eType="#//PlayerBoard" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BoardSN" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameDeck" eSuperTypes="#//Deck">
    <eOperations name="RemoveCard" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="removeCardSN" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="ReturnCard" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="returnCardSN" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="ShowGameDeck"/>
    <eOperations name="ShowGameStartDeckCards"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DeckOwner" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GameStartDeckCards" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Game">
    <eOperations name="ShowGame">
      <eParameters name="GameSN" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="ShowGameInDetail"/>
    <eOperations name="HaltGame"/>
    <eOperations name="ShowGameHand"/>
    <eOperations name="ShowGameBoard"/>
    <eOperations name="CheckGameStates" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Check each hero's health, if &lt;=0, we have a winner, and game over&#xD;&#xA;"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GameSN" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GameStates" eType="#//GameStates"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GameID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GameHasGameRule" lowerBound="1"
        eType="#//GameRule"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Player">
    <eOperations name="PlayCard">
      <eParameters name="cardindex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations name="OperateCard" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="thecard" eType="#//Card"/>
    </eOperations>
    <eOperations name="ClickNextTurnBtn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="DrawCard" lowerBound="1" upperBound="5" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eOperations name="OperateCard">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Use your on board card to attack your opponent's hero"/>
      </eAnnotations>
      <eParameters name="theHero" eType="#//Hero"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TotalWins" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PlayerHasDeck" lowerBound="1"
        eType="#//GameDeck" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CardsInHand" lowerBound="1"
        eType="#//GamePlayerHand" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PlayerHasOwnBoard" lowerBound="1"
        eType="#//PlayerBoard" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PlayerID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LastLogin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PlayerLevel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PlayerHasGameStartDeck"
        eType="#//Deck" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="PlayerHasDeckSet" upperBound="9"
        eType="#//Deck" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlayerBoard" eSuperTypes="#//Deck">
    <eOperations name="ShowPlayerBoard"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="BoardOwner" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CardStates">
    <eLiterals name="InDeck" value="1"/>
    <eLiterals name="InPlayerHand" value="2"/>
    <eLiterals name="Sleep" value="3"/>
    <eLiterals name="ReadyForAction" value="4"/>
    <eLiterals name="Dead" value="6"/>
    <eLiterals name="Acted"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hero">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HeroClass" lowerBound="1"
        eType="#//HeroClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HeroHealth" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="30"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HeroStates" eType="#//HeroStates"
        defaultValueLiteral="ReadyForAction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HeroAbility" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HeroDesc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HeroPower" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HeroStates">
    <eLiterals name="ReadyForAction" value="1"/>
    <eLiterals name="Acted" value="2"/>
    <eLiterals name="Dead" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GameStates">
    <eLiterals name="Created"/>
    <eLiterals name="Playing" value="1"/>
    <eLiterals name="Over" value="2"/>
    <eLiterals name="Halt" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GamePool">
    <eOperations name="ShowGames"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GamePoolHasGames" upperBound="-1"
        eType="#//Game" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GamePoolDesc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CardCollection">
    <eOperations name="ShowCollection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CollectionHasCards" upperBound="-1"
        eType="#//Card" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CollectionID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CollectionOwner" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameRule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="GameHasPlayers" lowerBound="2"
        upperBound="-1" eType="#//Player" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GameHasBoard" lowerBound="1"
        eType="#//GameBoard" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GameHasGameRule" lowerBound="1"
        eType="#//Game"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GameRuleDesc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GameRuleType" eType="#//GameType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameSetter"/>
  <eClassifiers xsi:type="ecore:EEnum" name="GameType">
    <eLiterals name="Standard"/>
    <eLiterals name="twovstwo" value="1"/>
    <eLiterals name="pve" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HeroAbility">
    <eLiterals name="MageAbility"/>
  </eClassifiers>
</ecore:EPackage>
